# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('data', models.CharField(max_length=300)),
                ('local', models.CharField(max_length=400)),
                ('cartaz', models.FileField(default='/inicial/static/img/logo.png', upload_to='')),
                ('tickets', models.CharField(max_length=1000)),
                ('evento_face', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=10000)),
                ('fotos', models.CharField(max_length=1000)),
            ],
        ),
    ]
